/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thedemo;

import java.io.IOException;
import thedemo.Controller.MainControl;

public class App {
    public static void main(String[] args) throws IOException {
        new MainControl();
        // URL fileLocation = App.class.getResource("/text/test.txt");

        // BufferedReader reader = new BufferedReader(new
        // InputStreamReader(fileLocation.openStream()));

        // System.out.println(reader.readLine());
    }
}
